version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  api-service:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        SERVICE: "api"
    entrypoint: "./api"
    restart: unless-stopped
    ports:
      - '3000:3000'
    expose:
      - 3000
    depends_on:
      - db
    env_file:
      - "./dev-postgres.env"

  scheduler-service:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        SERVICE: "scheduler"
    entrypoint: "./scheduler"
    restart: unless-stopped
    ports:
      - '4000:4000'
    expose:
      - 4000
    depends_on:
      - db
    env_file:
      - "./dev-postgres.env"

networks:
  default:
volumes:
  db:
    driver: local